name: Deploy Release to Production
run-name: Deploy ${{ github.ref_name }} to Production
concurrency: deploy-production
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-production]
jobs:
  deployment:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deploy to Penguin
        env:
          PENGUINCTL_APIURL: ${{ secrets.PENGUINCTL_APIURL }}
          PENGUINCTL_APITOKEN: ${{ secrets.PENGUINCTL_APITOKEN }}
        run: |
          make deploy-lms